# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
]

[prune]
  go-tests = true
  unused-packages = true

  # Don't prune helper scripts from code-generator
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  #revision = "977b11a0e9006feac85090aa8ee32481f46e94e8"
  branch = "move_to_crds"
  # Optional: an alternate location (URL or import path) for the project's source.
  source = "https://github.com/justinsb/cluster-api.git"


[[override]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.1"

[[override]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"


# Fix dep
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

#[[constraint]]
#  name = "k8s.io/api"
#  branch = "kubernetes-1.11.0"

#[[constraint]]
#  name = "k8s.io/client-go"
#  branch = "kubernetes-1.11.2"


#[[constraint]]
#  name = "k8s.io/code-generator"
#  branch = "release-1.9"
